### ISSUE TITLE
Setup Repo

### ISSUE THREAD

**Issue by artalat** [BlueBaseJS/core#135]
We need to complete the following chores to setup this repo before the final release of V5.

- [x] Add Semantic Releases
- [x] Add Updated Issue & Pull Request Templates
- [x] Add updated README.md
- [x] Technical docs and storybook automated publishing through travis

**Comment by ammarkhan967** [comment]
this will be pre-release not main release. this will config from pre-releases

**Comment by abubakarmani1** [comment]
@danial24 I have discussed with danyal and the code is briefed, moreover if in case of any ambiguities I can assist as required.

**Comment by artalat** [comment]
we cannot close it till this is resolved

**Comment by artalat** [comment]
Pre-release through semantic release: https://github.com/semantic-release/evolution/blob/release-workflows/_drafts/release-workflows.md#pre-releases
